#!/bin/sh
# Builds insta-focus.user.js from the extension's content script, so the
# desktop extension and the mobile userscript share exactly the same filter.
cd "$(dirname "$0")"
{
  cat <<'HEADER'
// ==UserScript==
// @name         Insta Focus – No Reels
// @namespace    swipe-it-vibe
// @version      1.0.0
// @description  Use Instagram for messages and posts only. Hides Reels everywhere.
// @match        https://www.instagram.com/*
// @match        https://instagram.com/*
// @run-at       document-start
// @grant        none
// ==/UserScript==
//
// Generated by build-userscript.sh from extension/content.js – edit that file.
// To change a setting, edit DEFAULTS below (enabled / blockSharedReels / hideExplore).

HEADER
  cat extension/content.js
} > insta-focus.user.js
echo "Wrote insta-focus.user.js"
